env: prod
http:
  port: 8000
mysql:
    uri: root:12345678@tcp(127.0.0.1:3306)/gva?charset=utf8mb4&parseTime=True&loc=Local
redis:
    addr: 127.0.0.1:6375
    password: ""
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s